config/routes.rb
Rails.application.routes.draw do
  resources :funcionarios do
    resources :contratos
    collection do
      get 'atuacao', to: 'funcionarios#atuacao'
    end
    collection do
      get 'contratos_por_funcionario', to: 'funcionarios#contratos_por_funcionario'
      get 'top5', to: 'contratos#top5'
    end
  end
  resources :contratos do
    collection do
      get 'buscar_por_id', to: 'contratos#buscar_por_id'
    end
  end
  resources :musicas

  resources :albums do
    collection do
      get 'buscar_por_id', to: 'albums#buscar_por_id'
    end
  end

  resources :integrantes
  resources :artista do
    resources :albums
    collection do
      get 'buscar_por_id', to: 'artista#buscar_por_id'
      get 'buscar_albuns_pelo_artista', to: 'artista#buscar_albuns_pelo_artista'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/musica.rb
class Musica < ApplicationRecord
  belongs_to :album, class_name: "Album", foreign_key: "album_id"

  has_many :musica_artistum
  has_many :artistum, through: :musica_artistum, dependent: :destroy

  has_many :musica_funcionarios
  has_many :funcionarios, through: :musica_funcionarios, dependent: :destroy

  validates :titulo, presence: true, length: { maximum: 100 }
  validates :duracao, presence: true
  validates :data_lancamento, presence: true
  validates :genero, presence: true
  validates :album, presence: true
  validates :funcionario_ids, presence: true
  validates :artistum_ids, presence: true
end

app/controllers/musicas_controller.rb
class MusicasController < ApplicationController
  before_action :set_musica, only: %i[ show edit update destroy ]

  # GET /musicas or /musicas.json
  def index
    @musicas = Musica.all
  end

  # GET /musicas/1 or /musicas/1.json
  def show
  end

  # GET /musicas/new
  def new
    @musica = Musica.new
  end

  # GET /musicas/1/edit
  def edit
  end

  # POST /musicas or /musicas.json
  def create
    @musica = Musica.new(musica_params)

    respond_to do |format|
      if @musica.save
        format.html { redirect_to musica_url(@musica), notice: "Musica was successfully created." }
        format.json { render :show, status: :created, location: @musica }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musicas/1 or /musicas/1.json
  def update
    respond_to do |format|
      if @musica.update(musica_params)
        format.html { redirect_to musica_url(@musica), notice: "Musica was successfully updated." }
        format.json { render :show, status: :ok, location: @musica }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicas/1 or /musicas/1.json
  def destroy
    @musica.destroy

    respond_to do |format|
      format.html { redirect_to musicas_url, notice: "Musica was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musica
      @musica = Musica.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def musica_params
      params.require(:musica).permit(:titulo, :duracao, :data_lancamento, :genero, :album_id, funcionario_ids: [], artistum_ids: [])
    end
end

app/helpers/musicas_helper.rb
module MusicasHelper
end

app/views/musicas/_form.html.erb
<%= form_with(model: musica) do |form| %>
  <% if musica.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(musica.errors.count, "error") %> prohibited this musica from being saved:</h2>

      <ul>
        <% musica.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :duracao, style: "display: block" %>
    <%= form.time_field :duracao %>
  </div>

  <div>
    <%= form.label :data_lancamento, style: "display: block" %>
    <%= form.date_field :data_lancamento %>
  </div>

  <div>
    <%= form.label :genero, style: "display: block" %>
    <%= form.text_field :genero %>
  </div>

  <div>
    <%= form.label :album_id, style: "display: block" %>
    <%= form.collection_select :album_id, Album.all, :id, :titulo, { prompt: 'Selecione um Album' }, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :funcionario_id, style: "display: block" %>
    <%= form.collection_check_boxes :funcionario_ids, Funcionario.all, :id, :nome, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :artista_id, style: "display: block" %>
    <%= form.collection_check_boxes :artistum_ids, Artistum.all, :id, :nome_artistico, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/musicas/_musica.html.erb
<div id="<%= dom_id musica %>">
  <p>
    <strong>Título:</strong>
    <%= musica.titulo %>
  </p>

  <p>
    <strong>Duração:</strong>
    <%= musica.duracao.strftime('%H:%M') %>
  </p>

  <p>
    <strong>Data de lançamento:</strong>
    <%= musica.data_lancamento.strftime('%d/%m/%Y') %>
  </p>

  <p>
    <strong>Gênero:</strong>
    <%= musica.genero %>
  </p>

  <p>
    <strong>Álbum:</strong>
    <%= musica.album_id %>
  </p>

</div>

app/views/musicas/edit.html.erb
<h1>Editar música</h1>

<%= render "form", musica: @musica %>

<br>

<div>
  <%= link_to "Mostrar música", @musica %> |
  <%= link_to "Voltar para músicas", musicas_path %>
</div>

app/views/musicas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Músicas</h1>

<div id="musicas">
  <% @musicas.each do |musica| %>
    <%= render musica %>
    <p>
      <%= link_to "Mostrar esta música", musica %>
    </p>
  <% end %>
</div>

<%= link_to "Nova música", new_musica_path %>

app/views/musicas/new.html.erb
<h1>Nova música</h1>

<%= render "form", musica: @musica %>

<br>

<div>
  <%= link_to "Voltar para músicas", musicas_path %>
</div>

app/views/musicas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @musica %>

<div>
  <%= link_to "Editar esta música", edit_musica_path(@musica) %> |
  <%= link_to "Voltar para músicas", musicas_path %>

  <%= button_to "Excluir esta música", @musica, method: :delete %>
</div>