config/routes.rb
Rails.application.routes.draw do
  resources :funcionarios do
    resources :contratos
    collection do
      get 'atuacao', to: 'funcionarios#atuacao'
    end
    collection do
      get 'contratos_por_funcionario', to: 'funcionarios#contratos_por_funcionario'
      get 'top5', to: 'contratos#top5'
    end
  end
  resources :contratos do
    collection do
      get 'buscar_por_id', to: 'contratos#buscar_por_id'
    end
  end
  resources :musicas

  resources :albums do
    collection do
      get 'buscar_por_id', to: 'albums#buscar_por_id'
    end
  end

  resources :integrantes
  resources :artista do
    resources :albums
    collection do
      get 'buscar_por_id', to: 'artista#buscar_por_id'
      get 'buscar_albuns_pelo_artista', to: 'artista#buscar_albuns_pelo_artista'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/integrante.rb
class Integrante < ApplicationRecord
  belongs_to :artista, class_name: 'Artistum', optional: true

  validates :nome, presence: true
  validates :cpf, presence: true, uniqueness: true, length: { is: 11 }, numericality: { only_integer: true }
  validates :funcao, presence: true
  #validates :artista, presence: true
end

app/controllers/integrantes_controller.rb
class IntegrantesController < ApplicationController
  before_action :set_integrante, only: %i[ show edit update destroy ]

  # GET /integrantes or /integrantes.json
  def index
    @integrantes = Integrante.all
  end

  # GET /integrantes/1 or /integrantes/1.json
  def show
  end

  # GET /integrantes/new
  def new
    @integrante = Integrante.new
  end

  # GET /integrantes/1/edit
  def edit
  end

  # POST /integrantes or /integrantes.json
  def create
    @integrante = Integrante.new(integrante_params)

    respond_to do |format|
      if @integrante.save
        format.html { redirect_to integrante_url(@integrante), notice: "Integrante was successfully created." }
        format.json { render :show, status: :created, location: @integrante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @integrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /integrantes/1 or /integrantes/1.json
  def update
    respond_to do |format|
      if @integrante.update(integrante_params)
        format.html { redirect_to integrante_url(@integrante), notice: "Integrante was successfully updated." }
        format.json { render :show, status: :ok, location: @integrante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @integrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /integrantes/1 or /integrantes/1.json
  def destroy
    @integrante.destroy

    respond_to do |format|
      format.html { redirect_to integrantes_url, notice: "Integrante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_integrante
      @integrante = Integrante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def integrante_params
      params.require(:integrante).permit(:nome, :cpf, :funcao, :artista_id)
    end
end

app/helpers/integrantes_helper.rb
module IntegrantesHelper
end

app/views/integrantes/_form.html.erb
<%= form_with(model: integrante) do |form| %>
  <% if integrante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(integrante.errors.count, "error") %> prohibited this integrante from being saved:</h2>

      <ul>
        <% integrante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :funcao, style: "display: block" %>
    <%= form.text_field :funcao %>
  </div>

  <div>
    <%= form.label :artista_id, style: "display: block" %>
    <%= form.text_field :artista_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/integrantes/_integrante.html.erb
<div id="<%= dom_id integrante %>">
  <p>
    <strong>Nome:</strong>
    <%= integrante.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= integrante.cpf %>
  </p>

  <p>
    <strong>Função:</strong>
    <%= integrante.funcao %>
  </p>

  <p>
    <strong>Artista:</strong>
    <%= integrante.artista_id %>
  </p>

</div>

app/views/integrantes/edit.html.erb
<h1>Editar integrante</h1>

<%= render "form", integrante: @integrante %>

<br>

<div>
  <%= link_to "Mostrar este integrante", @integrante %> |
  <%= link_to "Voltar para integrantes", integrantes_path %>
</div>

app/views/integrantes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Integrantes</h1>

<div id="integrantes">
  <% @integrantes.each do |integrante| %>
    <%= render integrante %>
    <p>
      <%= link_to "Mostrar este integrante", integrante %>
    </p>
  <% end %>
</div>

<%= link_to "Novo integrante", new_integrante_path %>

app/views/integrantes/new.html.erb
<h1>Novo integrante</h1>

<%= render "form", integrante: @integrante %>

<br>

<div>
  <%= link_to "Voltar para integrantes", integrantes_path %>
</div>

app/views/integrantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @integrante %>

<div>
  <%= link_to "Editar este integrante", edit_integrante_path(@integrante) %> |
  <%= link_to "Voltar para integrantes", integrantes_path %>

  <%= button_to "Excluir este integrante", @integrante, method: :delete %>
</div>