config/routes.rb
Rails.application.routes.draw do
  resources :funcionarios do
    resources :contratos
    collection do
      get 'atuacao', to: 'funcionarios#atuacao'
    end
    collection do
      get 'contratos_por_funcionario', to: 'funcionarios#contratos_por_funcionario'
      get 'top5', to: 'contratos#top5'
    end
  end
  resources :contratos do
    collection do
      get 'buscar_por_id', to: 'contratos#buscar_por_id'
    end
  end
  resources :musicas

  resources :albums do
    collection do
      get 'buscar_por_id', to: 'albums#buscar_por_id'
    end
  end

  resources :integrantes
  resources :artista do
    resources :albums
    collection do
      get 'buscar_por_id', to: 'artista#buscar_por_id'
      get 'buscar_albuns_pelo_artista', to: 'artista#buscar_albuns_pelo_artista'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>GRAVADORA - CADASTROS</h1> |
<%= link_to "Funcionários", funcionarios_path %> |
<%= link_to "Contratos", contratos_path %> |
<%= link_to "Artistas", artista_path %> |
<%= link_to "Álbuns", albums_path %> |
<%= link_to "Músicas", musicas_path %> |

<h1>GRAVADORA - BUSCAS</h1>

<h3>Buscar artista por ID</h3>
<p><b>Lógica da busca no PostgreSQL:</b> <i>SELECT * FROM artista WHERE id = artista_id;</i></p>
<%= form_with url: buscar_por_id_artista_path, method: :get do |form| %>
  <%= form.collection_select :artista_id, Artistum.all, :id, :nome_com_id, { prompt: 'Selecione um Artista' }, class: 'form-control' %>
  <%= form.submit "Buscar Artista" %>
<% end %>

<h3>Buscar Albuns pelo ID do artista</h3>
<p><b>Lógica da busca no PostgreSQL:</b> <i>SELECT * FROM albums WHERE artista_id = artista_id;</i></p>
<%= form_with url: buscar_albuns_pelo_artista_artista_path, method: :get do |form| %>
  <%= form.collection_select :artista_id, Artistum.all, :id, :nome_com_id, { prompt: 'Selecione um Artista' }, class: 'form-control' %>
  <%= form.submit "Buscar Álbuns" %>
<% end %>

<h3>Buscar Contrato por ID</h3>
<p><b>Lógica de busca no PostgreSql:</b> <i> Select * FROM contratos WHERE contrato_id = contrato_id;</i></p>
<%= form_with url: buscar_por_id_contratos_path, method: :get do |form| %>
  <%= form.collection_select :contrato_id, Contrato.all, :id, :id, { prompt: 'Selecione um Contrato' }, class: 'form-control' %>
  <%= form.submit "Buscar Contrato" %>
<% end %>

<h3>Buscar Álbuns por ID</h3>
<p><b>Lógica de busca no PostgreSql:</b> <i> Select * FROM albums WHERE album_id = album_id;</i></p>
<%= form_with url: buscar_por_id_albums_path, method: :get do |form| %>
  <%= form.collection_select :album_id, Album.all, :id, :nome_com_id, { prompt: 'Selecione um Álbum' }, class: 'form-control' %>
  <%= form.submit "Buscar Álbum" %>
<% end %>

<h3>Buscar Contratos por Funcionário</h3>
<p><b>Lógica da busca no PostgreSQL:</b> <i>SELECT c.* FROM funcionarios as f JOIN contrato_funcionarios as cf ON f.id = cf.funcionario_id
  JOIN contratos as c ON cf.contrato_id = c.id WHERE f.id = funcionario_id;</i></p>
<%= form_with url: contratos_por_funcionario_funcionarios_path, method: :get do |form| %>
  <%= form.collection_select :funcionario_id, Funcionario.all, :id, :nome_com_id, { prompt: 'Selecione um Funcionário' }, class: 'form-control' %>
  <%= form.submit "Buscar Contratos", class: "btn btn-primary" %>
<% end %>

<h3>Buscar Top 5 Maiores Contratos</h3>
<p><b>Lógica da busca no PostgreSQL:</b> <i>SELECT * FROM contratos ORDER BY valor DESC LIMIT 5;</i></p>
<%= link_to "Top 5 Maiores Contratos", top5_funcionarios_path, class: "btn btn-primary" %>

<h3>Buscar Atribuições do Funcionário pelo ID</h3>
<p><b>Lógica da busca no PostgreSQL:</b></p>
<p><b>Lógica da busca que conta as atribuições: </b><i>SELECT COUNT(DISTINCT c.id) AS total_contratos, COUNT(DISTINCT m.id) AS total_musicas, COUNT(DISTINCT a.id) AS total_albuns
  FROM funcionarios AS f
  LEFT JOIN contrato_funcionarios AS cf ON f.id = cf.funcionario_id
  LEFT JOIN contratos AS c ON cf.contrato_id = c.id
  LEFT JOIN musica_funcionarios AS mf ON f.id = mf.funcionario_id
  LEFT JOIN musicas AS m ON mf.musica_id = m.id
  LEFT JOIN album_funcionarios AS af ON f.id = af.funcionario_id
  LEFT JOIN albums AS a ON af.album_id = a.id
  WHERE f.id = 1;</i></p>
<p><b>Lógica da busca os Contratos nos quais o Funcionário está atribuido: </b><i>SELECT * FROM funcionarios AS f LEFT JOIN contrato_funcionarios AS cf ON f.id = cf.funcionario_id
  LEFT JOIN contratos AS c ON cf.contrato_id = c.id WHERE f.id = funcionario_id;</i></p>
<p><b>Lógica da busca os Música nos quais o Funcionário está atribuido: </b><i>SELECT * FROM funcionarios AS f LEFT JOIN musica_funcionarios AS mf ON f.id = mf.funcionario_id
  LEFT JOIN musicas AS m ON mf.musica_id = m.id WHERE f.id = funcionario_id;</i></p>
<p><b>Lógica da busca os Albuns nos quais o Funcionário está atribuido: </b><i>SELECT * FROM funcionarios AS f LEFT JOIN album_funcionarios AS af ON f.id = af.funcionario_id
  LEFT JOIN albums AS a ON af.album_id = a.id WHERE f.id = funcionario_id;</i></p>

<%= form_with url: atuacao_funcionarios_path, method: :get do |form| %>
  <%= form.collection_select :funcionario_id, Funcionario.all, :id, :nome_com_id, { prompt: 'Selecione um Funcionario' }, class: 'form-control' %>
  <%= form.submit "Buscar Atribuições" %>
<% end %>