config/routes.rb
Rails.application.routes.draw do
  resources :funcionarios do
    resources :contratos
    collection do
      get 'atuacao', to: 'funcionarios#atuacao'
    end
    collection do
      get 'contratos_por_funcionario', to: 'funcionarios#contratos_por_funcionario'
      get 'top5', to: 'contratos#top5'
    end
  end
  resources :contratos do
    collection do
      get 'buscar_por_id', to: 'contratos#buscar_por_id'
    end
  end
  resources :musicas

  resources :albums do
    collection do
      get 'buscar_por_id', to: 'albums#buscar_por_id'
    end
  end

  resources :integrantes
  resources :artista do
    resources :albums
    collection do
      get 'buscar_por_id', to: 'artista#buscar_por_id'
      get 'buscar_albuns_pelo_artista', to: 'artista#buscar_albuns_pelo_artista'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  has_many :contrato_funcionarios
  has_many :contratos, through: :contrato_funcionarios, dependent: :destroy

  has_many :album_funcionarios
  has_many :albums, through: :album_funcionarios, dependent: :destroy

  has_many :musica_funcionarios
  has_many :musicas, through: :musica_funcionarios, dependent: :destroy

  validates :nome, presence: true
  validates :cpf, presence: true, uniqueness: true, length: { is: 11 }, numericality: { only_integer: true }
  validates :salario, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cargo, presence: true

  def nome_com_id
    "#{nome} [ID #{id}]"
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  def atuacao
    id = if params[:id].present? then params[:id] else params[:funcionario_id] end
    @funcionario_atuacao = Funcionario.find(id)
    @contratos = @funcionario_atuacao.contratos
    @musicas = @funcionario_atuacao.musicas
    @albuns = @funcionario_atuacao.albums

    @total_contratos = @contratos.count
    @total_musicas = @musicas.count
    @total_albuns = @albuns.count
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  def contratos_por_funcionario
    @funcionario = Funcionario.find(params[:funcionario_id])
    @contratos = @funcionario.contratos
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy

    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :salario, :cargo)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :salario, style: "display: block" %>
    <%= form.number_field :salario %>
  </div>

  <div>
    <%= form.label :cargo, style: "display: block" %>
    <%= form.text_area :cargo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>">
  <p>
    <strong>Nome:</strong>
    <%= funcionario.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= funcionario.cpf %>
  </p>

  <p>
    <strong>Salário:</strong>
    <%= funcionario.salario %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= funcionario.cargo %>
  </p>

</div>

app/views/funcionarios/atuacao.html.erb
<h1>Atuações de Funcionário</h1>
<p style="color: green"><%= notice %></p>

<h3>Detalhes do Funcionários</h3>
<%= render @funcionario_atuacao %>
<br>
<h3>Atribuições:</h3>

<div>
  <h4>Total de Contratos: <%= @total_contratos %></h4>
  <%= render @contratos %>
</div>
<hr>
<div>
  <h4>Total de Músicas: <%= @total_musicas %></h4>
  <%= render @musicas %>
</div>
<hr>
<div>
  <h4>Total de Albuns: <%= @total_albuns %></h4>
  <%= render @albuns %>
</div>
<div>
  <%= link_to "Voltar para funcionários", funcionarios_path %>
</div>

app/views/funcionarios/contratos_por_funcionario.html.erb
<h1>Contratos do Funcionário <%= @funcionario.nome %></h1>

<% if @contratos.any? %>
  <% @contratos.each do |contrato| %>
    <div class="contract-details">
      <p><strong>Artista:</strong> <%= contrato.artista.nome_artistico %></p>
      <p><strong>Data de Início:</strong> <%= contrato.data_inicio %></p>
      <p><strong>Data de Fim:</strong> <%= contrato.data_fim %></p>
      <p><strong>Valor:</strong> <%= contrato.valor %></p>
      <p><strong>Clausulas:</strong> <%= contrato.clausulas %></p>
    </div>
    <hr>
  <% end %>
<% else %>
  <p>Nenhum contrato encontrado para este funcionário.</p>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editar funcionário</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Mostrar este funcionário", @funcionario %> |
  <%= link_to "Voltar para funcionários", funcionarios_path %>
</div>

app/views/funcionarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Funcionários</h1>

<div id="funcionarios">
  <% @funcionarios.each do |funcionario| %>
    <%= render funcionario %>
    <p>
      <%= link_to "Mostrar este funcionário", funcionario %>
    </p>
  <% end %>
</div>

<%= link_to "Novo funcionário", new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>Novo funcionário</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Voltar para funcionários", funcionarios_path %>
</div>

app/views/funcionarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @funcionario %>

<div>
  <%= link_to "Editar este funcionário", edit_funcionario_path(@funcionario) %> |
  <%= link_to "Voltar para funcionários", funcionarios_path %>

  <%= button_to "Excluir este funcionário", @funcionario, method: :delete %>
</div>